name: lestari_admin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  google_fonts: ^4.0.3
  sizer: ^2.0.15
  intl: ^0.18.0
  permission_handler: ^10.2.0
  equatable: ^2.0.5
  shared_preferences: ^2.0.17
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.4.2
  bloc: ^8.1.1
  loader_overlay: ^2.1.0
  flutter_bloc: ^8.1.2
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.7
  file_picker: ^5.2.6
  firebase_storage: ^11.0.15
  url_launcher: ^6.1.10
  model_viewer_plus: ^1.7.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
