// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYkjf3mysFuRs2TJrB8JBJamldXYsGTj0',
    appId: '1:159171602922:android:b44d2b56b62e60e43aaa93',
    messagingSenderId: '159171602922',
    projectId: 'lestari-42054',
    storageBucket: 'lestari-42054.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX9tWoUM3kQ55gAPgXq61MYf_DW-yE_jE',
    appId: '1:159171602922:ios:cc882681b76e253b3aaa93',
    messagingSenderId: '159171602922',
    projectId: 'lestari-42054',
    storageBucket: 'lestari-42054.appspot.com',
    androidClientId: '159171602922-687cb2159235n91on2koa739fusjma0j.apps.googleusercontent.com',
    iosClientId: '159171602922-m588ibo5obvqc5km98cfkmp6h4km27en.apps.googleusercontent.com',
    iosBundleId: 'com.midnights.lestariAdmin',
  );
}
